import Image from "next/image";
import Link from "next/link";
import getConfig from 'next/config';
import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

const { publicRuntimeConfig } = getConfig();
const basePath = publicRuntimeConfig.basePath || '';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lee Jae Hoon | Game developer portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <div className="navbar">
            <Link href={`${basePath}/#home`}>
              <Image
                className="logo"
                src={`${basePath}/yesman.png`}
                alt="Yesman"
                width={60}
                height={60}
              />
            </Link>
            <nav>
              <ul>
                <li>
                  <Link href={`${basePath}/#about`}>About</Link>
                </li>
                <li>
                  <Link href={`${basePath}/#projects`}>Projects</Link>
                </li>
                <li>
                  <Link href={`${basePath}/#activities`}>Activities</Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}